# Generated by Django 4.1.7 on 2023-03-07 12:35

import app.course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(null=True, upload_to=app.course.models.file_path_for_cover),
        ),
    ]
