# Generated by Django 4.1.7 on 2023-03-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
        ('course', '0005_soldcourse_course_soldcourse_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile'),
        ),
    ]
