# Generated by Django 4.1.7 on 2023-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
