# Generated by Django 4.1.7 on 2023-03-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_role'),
        ('course', '0007_lesson_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldcourse',
            name='profile',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
