# Generated by Django 4.1.7 on 2023-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Teacher'), (1, 'Student')], default=1),
        ),
    ]
